config/routes.rb
Rails.application.routes.draw do
  get 'contact/index'

  get 'about/index'

  resources :reviews
  resources :products

  root 'products#landing'

end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :description, :name, presence: true
  validates :price, numericality: {greater_than: 0}
  has_many :reviews

  def formatted_price
    format("%.2f", price)
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  def landing
    @products = Product.all
  end
  # GET /products/1
  # GET /products/1.json
  def show
    @review = Review.new
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :picture, :description, :price)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:comment, :product_id)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/about/index.html.erb
<!-- <link href='https://fonts.googleapis.com/css?family=Lemon' rel='stylesheet' type='text/css'> -->
<link href='https://fonts.googleapis.com/css?family=Chango' rel='stylesheet' type='text/css'>



<!--Navigation Bar-->
  <nav class="nav-wrap">
    <ul class="nav split">
      <li><a href="/">Home</a></li>
      <li><a href="/products">Shop |</a></li>
      <li><a href="/about/index">About Us |</a></li>
      <li><a href="/contact/index">Contact</a></li>
    </ul>
  </nav>



<div class="about">
<h1>About Us</h1>
<!-- <p>Find me in app/views/about/index.html.erb</p> -->
</div>



<div class="about-img">
  <%= image_tag("trio2.jpg") %>
</div>



<div class="about-us">

Project Zambezi was created by the trio known as the Wynos. Our aim was to create a platform where restaurant owners could highlight their dishes to the public. Many times when people are looking for a restaurant to visit, they read the menu online, but images look more appetizing than text.<br><br>

A restaurant owner using Project Zambezi would input their story or description of their restaurant and menu here.
</div>

app/views/contact/index.html.erb
<!-- <link href='https://fonts.googleapis.com/css?family=Lemon' rel='stylesheet' type='text/css'> -->
<link href='https://fonts.googleapis.com/css?family=Chango' rel='stylesheet' type='text/css'>


<!--Navigation Bar-->
  <nav class="nav-wrap">
    <ul class="nav split">
      <li><a href="/">Home</a></li>
      <li><a href="/products">Shop |</a></li>
      <li><a href="/about/index">About Us |</a></li>
      <li><a href="/contact/index">Contact</a></li>
    </ul>
  </nav>

  <div class="contact">
    <h1>Contact Us</h1>
  </div>


  <div class="contact-info">
    <!-- <h3>Contact Us</h3> -->
    <p>Zambezi Fruit Stand <br>
       5 Zambezi Way <br>
       Zambezi, Africa 55555<br>
       1-888-Zambezi
    </p>
  </div>


<div class="contact-form"
<%= form_for :article do |f| %>
 <p>
   <strong><%= f.label :Name %><br></strong>
   <%= f.text_field :name %>
 </p>

 <p>
  <strong><%= f.label :Email %><br></strong>
  <%= f.text_field :Email %>
 </p>

 <p>
   <strong><%= f.label :Message %><br></strong>
   <%= f.text_area :text %>
 </p>

 <p>
   <input type="button" value="Submit Message">
 </p>
<% end %>
</div>

<div class="contact-img">
  <%= image_tag("zambezi.png") %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zambezi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_area :picture %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/extra.html.erb
<!-- <table> -->
<tbody>
  <% @products.each do |product| %>
    <tr>
      <td><%= product.name %></td>
      <td><%= image_tag(product.picture) %></td>
      <!-- <td><%= product.picture %></td> -->
      <td><%= product.description %></td>
      <td>$<%= product.formatted_price %></td>
    </tr>
  <% end %>
</tbody>
</table>

app/views/products/index.html.erb
<!-- <link href='https://fonts.googleapis.com/css?family=Lemon' rel='stylesheet' type='text/css'> -->
<link href='https://fonts.googleapis.com/css?family=Chango' rel='stylesheet' type='text/css'>


<p id="notice"><%= notice %></p>

<!--Navigation Bar-->
  <nav class="nav-wrap">
    <ul class="nav split">
      <li><a href="/">Home</a></li>
      <li><a href="/products">Shop |</a></li>
      <li><a href="/about/index">About Us |</a></li>
      <li><a href="/contact/index">Contact</a></li>
    </ul>
  </nav>


<div class="list-page">
<h1>Listing Fruits</h1>
<br>
<br>
<br>

<div id="link">
<%= link_to 'Create New Menu Item', new_product_path %>
</div>
<br>
<br>
<br>
<table>
  <thead>
    <tr>
      <th>Name</th>  
      <!-- <th>Picture</th> -->
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>


  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <!-- <td><%= product.picture %></td> -->
        <!-- <td><%= product.picture %></td> -->
        <td><%= product.description %></td>
        <td>$<%= product.formatted_price %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


</div>

app/views/products/landing.html.erb
<link href='https://fonts.googleapis.com/css?family=Candal' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Lemon' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Chango' rel='stylesheet' type='text/css'>





<!--Navigation Bar-->
  <nav class="nav-wrap">
    <ul class="nav split">
      <li><a href="/">Home</a></li>
      <li><a href="/products">Shop |</a></li>
      <li><a href="/about/index">About Us |</a></li>
      <li><a href="/contact/index">Contact</a></li>
    </ul>
  </nav>






<!--Welcome!  -->
<div class="main-container">
  <image_tag("header.jpg") />
<h1>Project Zambezi<h1>
  <!-- <h3>Your online Fruit Stand</h3> -->
</div>


  <div>
    <ul class="product-container">
      <% @products.each do |product| %>
      <li class="products">
        <h3><%= product.name %></h3>
        <div class="product-image"><%= image_tag(product.picture) %></div>
        <div class="product-description">
        <p><%= product.description %> </p>
        <p>$<%= product.formatted_price %></p>
        </div>
      </li>
      <% end %>
    </ul>

</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <span class="sobig"><%= @product.name %></span>
</p>

<p>
  <strong>Picture:</strong>
  <div class="wyno-image"><%= image_tag(@product.picture) %></div>
</p>

<p>
  <strong>Description:</strong>
  <span class="sobig"><%= @product.description %></span>
</p>

<p>
  <strong>Price:</strong>
  <span class="sobig">$<%= @product.formatted_price %></span>
</p>

<!-- <h3>Reviews</h3>
<% @product.reviews.each do |review| %>
  <p>
    <%= review.comment %>
    <br>
    Added on: <%= review.created_at %>
  </p>
<% end %>

<h3>New Review</h3>
<%= render 'reviews/form' %> -->
<Br>
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>

  <% if @product.nil? %>
  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.text_field :product_id %>
  </div>

  <% else %>
    <%= f.hidden_field :product_id, disabled: true, value: @product.id %>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>


<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Comment</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.comment %></td>
        <td><%= review.product %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment:</strong>
  <%= @review.comment %>
</p>

<p>
  <strong>Product:</strong>
  <%= @review.product.name %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<% if @review.product.nil? %>
  <%= link_to 'Back', reviews_path %>
<% else %>
  <%= link_to 'Back', @review.product %>
<% end %>